### ISSUE TITLE
Remove the underline from the hover in footer

### ISSUE THREAD

**Issue by PoulavBhowmick03** [aniketsinha2002/DataGeek#456]
When you hover on an element in the footer, an underline appears with the glow up. The underline doesn't look nice, I want to remove that 

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/133862694/69c91904-2a30-4e74-9811-7140622fddda)

**Comment by PoulavBhowmick03** [comment]
@aniketsinha2002 can this be assigned?

**Comment by priyanka0815** [comment]
Hello @aniketsinha2002 , I am interested in this issue and would appreciate the opportunity to be assigned to it.

**Comment by Snigdha2712** [comment]
Please assign this issue to me under gssoc 23
