### ISSUE TITLE
[GSSOC'23]: Proper gap between courses

### ISSUE THREAD

**Issue by Naina047** [aniketsinha2002/DataGeek#535]
### Description

There is not enough gap between the courses mentioned. To make it more good for UX , I would like to work on this project.
I'm a GSSOC'23 contributor. Please assign me this task.

### Screenshots

![Screenshot 2023-06-20 114550](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/96466577/d1885e47-503f-4a43-8a25-946d82a5bf03)

**Comment by ratuladhikary21** [comment]
I would like to work on this issue. Please assign me with this

**Comment by sanketsur22** [comment]
I have gone through the issue and I am intrested to sole this issue. Im a GSSoC'23 contributor. kindly assign me this issue.
