### ISSUE TITLE
Navbar is distorted and there are many distortions.  

### ISSUE THREAD

**Issue by sharmavikas4** [aniketsinha2002/DataGeek#536]
### Description

The website has become distorted, everything is looking distorted. Please assign me this issue I want to work on it.

### Screenshots

![Screenshot (25)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/103022164/1b0d2c97-37dc-48f6-918f-b7a1cb7e240c)
![Screenshot (26)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/103022164/88b6e61d-1f66-4067-838c-12973f8d634b)
![Screenshot (27)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/103022164/43d6b69a-9d25-4a8c-a2cb-d597f946ea0e)
![Screenshot (28)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/103022164/b18b9125-e3ff-4b5c-863f-c3dd44159be7)
![Screenshot (29)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/103022164/595d7481-f427-4ed5-a1f0-27019ccb3996)

**Comment by Humaira-Sadia** [comment]
Hi @aniketsinha2002 , I would be very happy to contribute to this project. I have sufficient knowledge of JavaScript, Bootstrap, and CSS, and I believe I can create a beautiful and user-interacting responsive UI for the navbar. and social buttons You can check out my work here: link: https://humaira-sadia.github.io/website/
please assign this issue to me :)
