### ISSUE TITLE
Making the footer responsive  

### ISSUE THREAD

**Issue by Srija-Burugula** [aniketsinha2002/DataGeek#541]
### Description

The buttons present in the footer are not redirecting. I would like to work on this issue under GSSoC'23. Please assign this issue to me.

**Comment by Humaira-Sadia** [comment]
Hi @aniketsinha2002 , I would be very happy to contribute to this project. I have sufficient knowledge of JavaScript, Bootstrap, and CSS, and I believe I can create a beautiful and user-interacting responsive footer displaying all the social and other important data. 
Please assign this issue to me :)
