### ISSUE TITLE
Navbar and footer not align

### ISSUE THREAD

**Issue by AlabhyaG** [aniketsinha2002/DataGeek#544]
### Description

The navbar is vertically aligned instead of horizontal and also it is in between the page rather than at the top of the page.
The navbar should be at the top and horizontally aligned.

The footer is also not aligned properly as, it is aligned as a list rather than a typical footer

### Screenshots

For Navbar:
![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/98676224/49716a87-28f1-45d6-aa19-8510928ef37a)

For Footer
![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/98676224/b326660c-1ee5-40e2-b15b-a70ea26884ce)

**Comment by Shaba1406** [comment]
I want to Fix the footer section of the website under gssoc 23 please assign it to me  @aniketsinha2002
