### ISSUE TITLE
SEO of the Complete Website

### ISSUE THREAD

**Issue by Girishnikam** [aniketsinha2002/DataGeek#550]
### Description

[GSSoC 2023] SEO-friendly website can increase website credibility, improve user experience and get more users on our website. For making the website SEO friendly I'll like to implement following things

- Optimize the title tags and meta descriptions
- Using keywords in the website content (will perform proper research for keywords across all the search engines)
- Include keyword-rich anchor text in links
- Clean up and organize the complete code

Find the attachment of example, how optimization will help to boost performance of the website

### Screenshots

![SEO Uses](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/84145346/3c686c5e-1308-4c30-9843-220414994d51)

**Comment by aniketsinha2002** [comment]
@Girishnikam  Assigned !!
