### ISSUE TITLE
[FEATURE] Adding logo in footer 

### ISSUE THREAD

**Issue by Dimple-Choudhary** [aniketsinha2002/DataGeek#554]
### Description

Can I add the logo in the footer, when the website will be fixed?

**Comment by Pallavi-star2002** [comment]
I want to work on this issue please give me  chance

**Comment by Pratipada013** [comment]
![Screenshot (188)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/106165315/dd6b469f-0b84-4d2a-8e46-0b2bb4df8b80)

**Comment by lavi20** [comment]
I would like to a solve this issue . Please assign me this issue.
