### ISSUE TITLE
Fixing design Issue

### ISSUE THREAD

**Issue by priyanka0815** [aniketsinha2002/DataGeek#556]
### Description

Hello Mentors, I found few issue in the web page and want to fix them under the GSSOC'23 so can you please assign me that task so I can Fix them.
Issues are :
adding page sharing button
File not found Error
Fixing Navigation bar
adding page sharing button
Fixing Student, Courses, and awards display Fields 

### Screenshots
![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/107804677/31e84586-ec59-44bf-b243-9789bd9ff0fb)

**Comment by govindgupta1912** [comment]
I also want to work on this issue please assign me this project
