### ISSUE TITLE
Improving the content in the display of data Sc 1,data Sc2,data Sc3 

### ISSUE THREAD

**Issue by Shanukumar2929** [aniketsinha2002/DataGeek#558]
I also wanna work on these issue under gssoc'23

![Screenshot (50)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/98840506/b12d2d01-25ce-4fb0-ac59-8ea9d1b68f2d)
![Screenshot (50)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/98840506/83f8927f-ede3-4528-8a90-5a68e050f2c3)
these contents needs to be changed

**Comment by sakshimaluskar2** [comment]
I want Improving the content int the display of data Sc1 , data Sc2 , data Sc3.

Solution -
We can improving data by adding  related  course content related to Data Science.
We can add following course with their description.
Introduction to Data Science: A foundational course that covers the basics of data science, including data manipulation, data analysis, and data visualization techniques.

Machine Learning: This course introduces the principles and algorithms used in machine learning, including supervised and unsupervised learning, regression, classification, and clustering.

Data Visualization: Focuses on the principles and techniques of visualizing data effectively to communicate insights and patterns.

It's important to provide a comprehensive description of each course, including learning objectives, prerequisites, duration, and any certifications or credentials associated with the course. Additionally, including information about the instructors, testimonials from past students, and pricing options can help visitors make informed decisions about which courses to pursue.

![Datatec](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/128711718/f13220f7-17d8-46ee-832c-4e133456ff2a)
Please assign me this issue under GSSoC'23.

**Comment by sakshimaluskar2** [comment]
Hey @aniketsinha2002 I will be able to this , Please assign this issue to me.
