### ISSUE TITLE
[FEATURE]  Add back to home button on Contact us page

### ISSUE THREAD

**Issue by SubhamB2003** [aniketsinha2002/DataGeek#598]
### Description

Hey, there is not back to home button present you can check below and I also changed the UI of the vertical scrollbar.
![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/94003231/ac69942e-1fa0-42c0-8b4f-be87e7d1bd52)

Please assign it to me

**Comment by Aditi-P22** [comment]
I would like to work on this project. Please assign this issue to me under gssoc'23.
