### ISSUE TITLE
[FEATURE] <description> Imrprove the contact us form

### ISSUE THREAD

**Issue by Shr-reny** [aniketsinha2002/DataGeek#604]
### Description

We can improve the contact us form by improving the template and also adding compulsory update to the the name and e-mail spaces. We can add space for social account links too.

**Comment by sakshimaluskar2** [comment]
I want to improve the contact us form.

solution-
Contact Form Fields: The form typically includes fields where users can enter their name, email address, subject, and message. These fields are essential for capturing the necessary information to respond to the inquiry or request effectively.

Message Content: The message field should be designed to accommodate a reasonable amount of text, allowing users to provide detailed information, inquiries, or feedback. Additionally, consider including clear instructions or guidelines to help users provide relevant information and structure their messages appropriately.

Optional Fields: Depending on the specific needs of the data science website, additional fields can be included in the contact form. For example, you might consider including an optional field for users to specify their affiliation, reason for contact, or their level of expertise in data science.
![datasc](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/128711718/82eb6d1b-b604-4bfc-b3fa-a336d6f6f419)
Please assign me this under GSSoC'23.

**Comment by sakshimaluskar2** [comment]
Hey @aniketsinha2002 I will be able to do this , please assign this issue to me.
