### ISSUE TITLE
Contact Us page fonts to be changed

### ISSUE THREAD

**Issue by ShikhaaT44** [aniketsinha2002/DataGeek#607]
### Description

The fonts of the Contact Us page are different than the ones in the whole website.

### Screenshots

![bug1 2](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/89783531/c0bc0edb-1338-4074-b8ce-2d9e2a1245e4)

Please assign this issue to me under GSSoC '23

**Comment by AshitaBidkar** [comment]
I want to work on this issue, kindly assign it to me.
