### ISSUE TITLE
[FEATURE] <Improve Navbar>

### ISSUE THREAD

**Issue by Neha5679** [aniketsinha2002/DataGeek#623]
### Description

I want to improve navbar font size, style, sine up section is not showing properly.

### Screenshots

![Screenshot (86)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/129548970/33e66a5e-1879-40b5-9f86-74d20afc4e0d)

**Comment by ParthMadhvani2** [comment]
hey, I have sent the pull request please accept it and assign this issue to me under GSSoC'23.
