### ISSUE TITLE
Contact page navbar

### ISSUE THREAD

**Issue by BhartiNagpure** [aniketsinha2002/DataGeek#626]
### Description

In contact us page there is no backbutton and also not a navbar so that user cannot backout thats why i would like to add navbar in contact us page.

please assign me this issue under GSSoC;23 tag.

**Comment by ParthMadhvani2** [comment]
I am a GSSOC'23 contributor and have changed the navbar on the contact us page. As well changed some code that was not correctly written and changed the UI as the colour was not matching. So can you please accept my pull request?
And please assign me this issue under GSSoC;23 tags.
