### ISSUE TITLE
[FEATURE]  Want to add Password Hide/Show button in login and signup page

### ISSUE THREAD

**Issue by HimanshuNarware** [aniketsinha2002/DataGeek#628]
### Description

##Description
The login and Sign page does not have any button which use to show and hide passwords, I want to work on this feature please assign me this issue. This feature will improve the readability of the website.

##Screenshot

### Screenshots

![40](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/83147410/a9322be6-e12b-4c5e-9061-832e5cf1f592)
![41](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/83147410/497b5de5-ae70-4729-a1b2-0d9297eb22a1)

**Comment by sakshimaluskar2** [comment]
I want to add password hide /show button in login and signup page.

Description -
   The password hide button in a login or signup form is typically used to provide users with the option to conceal the characters they are entering as their password. It enhances security and privacy by preventing others from seeing the password while it is being typed.
   The password hide button typically appears as an eye icon placed next to the password input field. When users click on it, the password characters are replaced with asterisks or bullets, preventing anyone from seeing the actual characters being entered.

![pass1](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/128711718/6ec234bb-6a04-44e7-b94e-6eba617c954f)
![pass2](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/128711718/81d4e9b5-c7cc-4888-81b6-27ab402fe2be)


Please assign me this issue under GSSoC'23.

**Comment by sakshimaluskar2** [comment]
Hey @aniketsinha2002 I will be able to do this, Please assign this issue to me.
