### ISSUE TITLE
Fix the Footer

### ISSUE THREAD

**Issue by blindaks** [aniketsinha2002/DataGeek#632]
### Description

The footer is broken.

### Screenshots

![Screenshot (33)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/128223364/b1d5a91e-39b4-46e1-82b8-642f42894a91)

**Comment by blindaks** [comment]
@aniketsinha2002 Please assign this issue to me.

**Comment by Manish12-verma** [comment]
please assign this issue to me ,I want to fix it

**Comment by ParthMadhvani2** [comment]
please assign this task to me under GSSoC'23 as I am a contributor.
