### ISSUE TITLE
[FEATURE] Add GitHub with other socials

### ISSUE THREAD

**Issue by blindaks** [aniketsinha2002/DataGeek#635]
### Description

I want to add GitHub with the other socials in the footer section.

### Screenshots

![Screenshot (48)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/128223364/4bb01f75-fad9-4287-844e-11caadd16a7b)

**Comment by blindaks** [comment]
@aniketsinha2002 Please assign this issue to me under GSSOC'23.

**Comment by Vaishwanavi** [comment]
please assign me this issue under GSSOC'23.
