### ISSUE TITLE
Navbar Issue

### ISSUE THREAD

**Issue by kumarkshitij171** [aniketsinha2002/DataGeek#652]
### Description

Navigation bar content coincides with other body contents while scrolling.
 

### Screenshots

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/113905269/effd7938-c4e1-402f-acd8-a7ddae65f8a9)

**Comment by kumarkshitij171** [comment]
assign me for this bug fixing issue.

**Comment by AryanShriv** [comment]
I fixed it
