### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by Harshu467** [aniketsinha2002/DataGeek#657]
### Description

As of now current contact us form is not so much good , we can make it more better UI

### Screenshots

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/89975347/7f3f0f60-aaa9-4df8-8d27-585fa791bc20)

**Comment by Harshu467** [comment]
Assign it to me

**Comment by Harshsaini001** [comment]
I want to add add hover effects in footer icons. Please assign this issue to me

**Comment by Ganaik2004** [comment]
@aniketsinha2002  i want to work on this issue. Please assign it to me.
