### ISSUE TITLE
[FEATURE]  Want to improve the hover effect on the footer  content

### ISSUE THREAD

**Issue by HimanshuNarware** [aniketsinha2002/DataGeek#658]
### Description

- I want to add left-to-right underline animation on the hover effect
- Currenlty the hover effect have underline but it missing the effect of  left to right animation

### Screenshots

![69](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/83147410/d9eec058-6ebd-48f0-b86f-d4f0c204c052)

**Comment by Salonijain2210** [comment]
I want to work o this project , please allow me the opportunity to work on this part.
