### ISSUE TITLE
[FEATURE] Lack of Responsiveness on the Website for Different Screen Sizes

### ISSUE THREAD

**Issue by Tharun-nennavath** [aniketsinha2002/DataGeek#668]
### Description

The website currently lacks responsiveness, making it challenging for the website to adapt appropriately to different screen sizes and devices. As a result, users accessing the website from various devices such as  tablets, and smartphones may experience distorted layouts, overlapping content, or elements not fitting within the screen, leading to a suboptimal user experience.

### Screenshots

![Screenshot 2023-07-20 234940](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/124525175/033d32e9-f3d7-40f7-b49e-7d45c169a35a)

**Comment by Tharun-nennavath** [comment]
Please consider assigning me this issue so that I can actively contribute to resolving the problem and enhancing the website's overall user experience.

**Comment by vansh-attri** [comment]
Hi, Can you please assign me this issue?
