### ISSUE TITLE
[FEATURE]Enhancing the Contact Us Page 

### ISSUE THREAD

**Issue by akankshachanana1** [aniketsinha2002/DataGeek#677]
### Description

Currently the hover effect on Contact Us Page is too subtle.I want to work on this issue by adding hover effect(raising them a little bit and changing cursor to pointer when hovered).
I will also add  more interactive hover effect on socials (according to there UI)

### Screenshots

https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/127978268/614cc6ef-a4e5-42f7-8bca-21ba04437767

**Comment by AshitaBidkar** [comment]
I want to work on this issue, kindly assign it to me.
