### ISSUE TITLE
[FEATURE] Add Home button from contact us page

### ISSUE THREAD

**Issue by pavitrachavda97** [aniketsinha2002/DataGeek#678]
### Description

There is no way to move back from contact us page. I want to add Home page button in contact us page so that user can move easily from contact us page to home page.

### Screenshots

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/91004608/1c1af631-e13b-4a37-9f98-b0c3dcebd8c1)

**Comment by karandeep4423** [comment]
can anybody assign this ?
