### ISSUE TITLE
Improve Navbar

### ISSUE THREAD

**Issue by Anuragwagh** [aniketsinha2002/DataGeek#681]
### Description

The Navbar Sign in Buttons is improper going out of window and on oter pages its look like overlapping, Assign me to make it better.

### Screenshots

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/56196363/d5a00b20-924b-49b0-8851-97661125f168)

![image](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/56196363/bfd01929-1e93-4885-881e-f5d7d76d0edf)

**Comment by Ganaik2004** [comment]
@aniketsinha2002  i want to work on this issues .please assign it to me.

**Comment by Chawlaradhika** [comment]
Hi I'd like to work on this issue if it is not fixed yet, please assign it to me
