### ISSUE TITLE
making the social sites logos colourfull

### ISSUE THREAD

**Issue by mahesh-barapatre** [aniketsinha2002/DataGeek#698]
### Description

the logos of the social media sites are black and white that doesn't match with the colourfull and attractive color scheme of the website....
so i can change the logos to attractive ones

### Screenshots

![Screenshot (105)](https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/97560633/56200ef9-84d0-4bb5-b00f-e38480268b7c)

**Comment by mahesh-barapatre** [comment]
assign me this issue under gssoc23 label

**Comment by AshitaBidkar** [comment]
I want to work on this issue, kindly assign it to me.
