### ISSUE TITLE
Top to arrow button Hiding

### ISSUE THREAD

**Issue by parasss19** [aniketsinha2002/DataGeek#721]
### Description

- The top to arrow button is hiding righnow as its overlapped by courses cards

### Screenshots

https://github.com/aniketsinha2002/DataScienceWebsite.github.io/assets/101205226/dddca2d4-7b91-4dec-aa63-2635b533a74b

**Comment by parasss19** [comment]
Hey @aniketsinha2002 Please reivew it ASAP so that i will complete it fast

**Comment by Ganaik2004** [comment]
@aniketsinha2002  I want to work on this issue can you please assign it to me.
